### ISSUE TITLE
Extend Spec to include choices for Args

### ISSUE THREAD

**Issue by miguelmig** [jdx/usage#138]
Clap has the concept of possible values when an argument is a `Enum` which can be extracted using `arg.get_possible_values`.

A new option for the `arg` element to include such choices could be implemented for tools like [Fig](https://fig.io/docs/reference/arg#suggestions) to suggest only the valid options for such argument,

**Comment by jdx** [comment]
isn't that the "choices" property on args? https://usage.jdx.dev/spec/reference/arg#arg

**Comment by miguelmig** [comment]
Oh okay so it's already a property, it's just that usage doesn't export it then. A `mise.usage.kdl` doesn't contain the choices from what I've seen

**Comment by jdx** [comment]
https://github.com/jdx/mise/blob/612bbd0374bed208752cda8674ad192b5886fde9/mise.usage.kdl#L185

**Comment by miguelmig** [comment]
Interesting, when I generated it, it didn't include it as you can see in the screenshot
<img width="713" alt="image" src="https://github.com/user-attachments/assets/031b0e3d-8552-4a1f-9fd7-073f2ca74026">

<img width="938" alt="image" src="https://github.com/user-attachments/assets/f4819a4f-6950-49ab-ad82-14ff43e68aa3">

**Comment by jdx** [comment]
make sure usage and mise are up-to-date

**Comment by miguelmig** [comment]
Yep that was it, somehow my forks were not sync'ed. Thanks!
