### ISSUE TITLE
Error about unexpected argument while generating completions

### ISSUE THREAD

**Issue by aaronsky** [jdx/usage#142]
Hi – wanted to make sure I'm not missing anything here. I've been following the project for a little while now and am excited for the 1.0 release. I wrote up a kdl spec and tried to run `usage` on it in the same way as is documented on the website, and I got this error:

```shell
❯ usage g completion fish -f ./bazel.usage.kdl
error: unexpected argument '-f' found

  tip: to pass '-f' as a value, use '-- -f'

Usage: usage generate completion [OPTIONS] <SHELL> <BIN>

For more information, try '--help'.
```

version info:

```
❯ usage --version
usage-cli 1.0.0
```

Is this expected? I looked at the code and couldn't find this flag on this command, and considering this very similar invocation is in mise's codebase, I figure I am doing something silly.

**Comment by jdx** [comment]
ah you need to give it a bin name, so `usage g completion fish bazel -f ./bazel.usage.kdl`

**Comment by aaronsky** [comment]
Thanks. I tried this on 1.0 but it still didn't work.

```
❯ usage g completion fish bazel -f ./bazel.usage.kdl
error: unexpected argument '-f' found

  tip: to pass '-f' as a value, use '-- -f'

Usage: usage generate completion [OPTIONS] <SHELL> <BIN>

For more information, try '--help'.
```
