### ISSUE TITLE
Get space-separated args

### ISSUE THREAD

**Issue by dorencambia** [jdx/usage#169]
Is there any convenient way to get the value of post-parsed arguments without them being converted to comma-separated?

With the following script "myscript.sh":

```sh
#!/usr/bin/env bash
#USAGE flag "-d --debug" help="Turn debug on"
#USAGE arg "[args]" var=true help="Arguments to pass to script"
echo "debug is $usage_debug"
echo "usage_args is $usage_args"
echo "passed $*"
```
Running `usage bash myscript.sh foo bar -d` prints:

```
debug is true
usage_args is foo,bar
passed foo bar -d
```

How would I get to the value `foo bar`?

Dealing with `$*` directly means I'd need to handle parsing all the args and flags manually. And doing something like `echo "$usage_args" | tr ',' ' '` will not work right if the passed args contains any commas.

**Comment by jdx** [comment]
this is a bug, it should be spaces

**Comment by dorencambia** [comment]
Wow, incredible response time! Thanks for fixing this
